build:
	@echo Start bulding ...
	docker compose -f local.yml up --build -d --remove-orphans
	@echo End building

up:
	@echo docker compose up...
	docker compose -f local.yml up -d
	@echo docker compose finished...

down:
	@echo docker compose down...
	docker compose -f local.yml down 
	@echo docker compose finished...
